#!/usr/bin/env python
"""Nekbot, el bot modulable multiprotocolo.
"""
import argparse
import logging
import os
import sys
from nekbot.core import NekBot

try:
    import nekbot
except:
    sys.path.append(os.path.abspath(os.path.dirname(__file__) + '../'))

__author__ = 'nekmo'

if __name__ == '__main__':
    #parse command line arguements
    parser = argparse.ArgumentParser(description=__doc__)

    # Niveles de logging
    parser.add_argument('-q', '--quiet', help='set logging to ERROR',
                        action='store_const', dest='loglevel',
                        const=logging.ERROR, default=logging.INFO,
                        )
    parser.add_argument('-d', '--debug', help='set logging to DEBUG',
                        action='store_const', dest='loglevel',
                        const=logging.DEBUG, default=logging.INFO)
    parser.add_argument('-v', '--verbose', help='set logging to COMM',
                        action='store_const', dest='loglevel',
                        const=5, default=logging.INFO)


    logging.basicConfig(level=logging.DEBUG)
    nekbot = NekBot().start()
    try:
        nekbot.loop()
    except (KeyboardInterrupt, SystemExit):
        nekbot.close()
